# Generated by Django 5.2.4 on 2025-07-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50, verbose_name='Event title')),
                ('date', models.DateField(verbose_name='Date of event')),
                ('start_time', models.TimeField(verbose_name='Start time of the event')),
                ('end_time', models.TimeField(verbose_name='End time of the event')),
            ],
        ),
    ]
